#!/usr/bin/env bash
# merge-blueprint.sh — Merge 4A architecture blueprint temporary segment files into a final output file
#
# Usage:
#   bash merge-blueprint.sh [-d DIR] [-s SCENE] [-o OUTFILE] [-k]
#
# Options:
#   -d DIR      Directory containing temporary files (default: current directory .)
#   -s SCENE    Scene name, used for filename 4a-blueprint-{SCENE}.md (default: blueprint)
#   -o OUTFILE  Specify full output path directly (overrides -d/-s)
#   -k          Keep temporary files (for debugging; default is to delete)
#
# Examples:
#   bash merge-blueprint.sh -s my-project
#   bash merge-blueprint.sh -d /path/to/docs -s my-project
#   bash merge-blueprint.sh -o /path/to/4a-final.md
#   bash merge-blueprint.sh -s my-project -k

set -euo pipefail

# -- Defaults ----------------------------------------------------------------------
DIR="."
SCENE="blueprint"
OUTFILE=""
KEEP_TMP=false

# -- Parse arguments ---------------------------------------------------------------
while getopts "d:s:o:k" opt; do
  case $opt in
    d) DIR="$OPTARG" ;;
    s) SCENE="$OPTARG" ;;
    o) OUTFILE="$OPTARG" ;;
    k) KEEP_TMP=true ;;
    *) echo "Usage: $0 [-d DIR] [-s SCENE] [-o OUTFILE] [-k]" >&2; exit 1 ;;
  esac
done

# -- Resolve output path -----------------------------------------------------------
DIR="$(cd "$DIR" && pwd)"

if [[ -z "$OUTFILE" ]]; then
  OUTFILE="$DIR/4a-blueprint-$SCENE.md"
fi

# -- Segment definitions (fixed order) --------------------------------------------
declare -a FILES=("_tmp_ba.md" "_tmp_da.md" "_tmp_aa.md" "_tmp_matrix.md" "_tmp_verify.md")
declare -a HEADINGS=(
  "## 1. BA Layer Table"
  "## 2. DA Layer Table"
  "## 3. AA Layer Table"
  "## 4. N:1:1 Mapping Matrix"
  "## 5. Tri-Architecture Alignment Verification Table"
)

# -- Pre-check: at least one temp file must exist ----------------------------------
found=0
for f in "${FILES[@]}"; do
  [[ -f "$DIR/$f" ]] && ((found++)) || true
done

if [[ $found -eq 0 ]]; then
  echo "Error: No temporary files (_tmp_*.md) found in directory: $DIR" >&2
  exit 1
fi

# -- Assemble and write output -----------------------------------------------------
{
  echo "# 4A Enterprise Architecture Blueprint - $SCENE"
  echo ""
  echo "> This file was auto-generated by merge-blueprint.sh at $(date '+%Y-%m-%d %H:%M:%S')"
  echo ""

  for i in "${!FILES[@]}"; do
    f="${FILES[$i]}"
    path="$DIR/$f"
    heading="${HEADINGS[$i]}"

    if [[ -f "$path" ]]; then
      line_count=$(wc -l < "$path")
      echo "---"
      echo ""
      echo "$heading"
      echo ""
      cat "$path"
      echo ""
      echo "  ✓ Merged: $f (${line_count} lines)" >&2
    else
      echo "Warning: Temporary file not found, skipped: $f" >&2
    fi
  done
} > "$OUTFILE"

echo ""
echo "✓ Merge complete: $OUTFILE"

# -- Clean up temp files -----------------------------------------------------------
if [[ "$KEEP_TMP" == false ]]; then
  for f in "${FILES[@]}"; do
    p="$DIR/$f"
    if [[ -f "$p" ]]; then
      rm -f "$p"
      echo "  ✓ Deleted: $f"
    fi
  done
  echo "✓ Temporary files cleaned up"
else
  echo "(-k mode: temporary files retained)"
fi

echo ""
echo "Final blueprint file: $OUTFILE"
