<#
.SYNOPSIS
    Merge 4A architecture blueprint temporary segment files into a final output file.

.DESCRIPTION
    Combines the segment files written by the AI Agent (_tmp_ba.md / _tmp_da.md /
    _tmp_aa.md / _tmp_matrix.md / _tmp_verify.md) in order into a single complete
    blueprint Markdown file, then automatically deletes all temporary files.

.PARAMETER Dir
    Directory containing temporary files. Defaults to the current directory (.).

.PARAMETER Scene
    Business scenario name, used to generate the final filename: 4a-blueprint-{Scene}.md.
    Defaults to "blueprint".

.PARAMETER OutFile
    Specify the full path for the final output file. If provided, Dir and Scene
    filename logic is ignored.

.PARAMETER KeepTmp
    If specified, temporary files are not deleted after merge (for debugging).

.EXAMPLE
    .\merge-blueprint.ps1 -Scene my-project

.EXAMPLE
    .\merge-blueprint.ps1 -Dir "C:\path\to\docs" -Scene my-project

.EXAMPLE
    .\merge-blueprint.ps1 -OutFile "D:\output\4a-final.md"

.EXAMPLE
    .\merge-blueprint.ps1 -Scene my-project -KeepTmp
#>

[CmdletBinding()]
param(
    [string] $Dir     = ".",
    [string] $Scene   = "blueprint",
    [string] $OutFile = "",
    [switch] $KeepTmp
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# -- 1. Resolve output path -------------------------------------------------------
$dir = Resolve-Path $Dir | Select-Object -ExpandProperty Path

if ($OutFile -ne "") {
    $outPath = $OutFile
} else {
    $outPath = Join-Path $dir "4a-blueprint-$Scene.md"
}

# -- 2. Define segment order -------------------------------------------------------
$sections = @(
    [PSCustomObject]@{ File = "_tmp_ba.md";     Heading = "## 1. BA Layer Table" }
    [PSCustomObject]@{ File = "_tmp_da.md";     Heading = "## 2. DA Layer Table" }
    [PSCustomObject]@{ File = "_tmp_aa.md";     Heading = "## 3. AA Layer Table" }
    [PSCustomObject]@{ File = "_tmp_matrix.md"; Heading = "## 4. N:1:1 Mapping Matrix" }
    [PSCustomObject]@{ File = "_tmp_verify.md"; Heading = "## 5. Tri-Architecture Alignment Verification Table" }
)

# -- 3. Pre-check: at least one temp file must exist -------------------------------
$found = $sections | Where-Object { Test-Path (Join-Path $dir $_.File) }
if ($found.Count -eq 0) {
    Write-Error "No temporary files (_tmp_*.md) found in directory: $dir"
    exit 1
}

$missing = $sections | Where-Object { -not (Test-Path (Join-Path $dir $_.File)) }
if ($missing.Count -gt 0) {
    Write-Warning "The following temporary files are missing; corresponding sections will be skipped:"
    $missing | ForEach-Object { Write-Warning "  - $($_.File)" }
}

# -- 4. Assemble content -----------------------------------------------------------
$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("# 4A Enterprise Architecture Blueprint - $Scene")
$lines.Add("")
$lines.Add("> This file was auto-generated by merge-blueprint.ps1 at $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
$lines.Add("")

foreach ($s in $sections) {
    $filePath = Join-Path $dir $s.File
    if (Test-Path $filePath) {
        $content = Get-Content $filePath -Encoding UTF8

        $lines.Add("---")
        $lines.Add("")
        $lines.Add($s.Heading)
        $lines.Add("")
        foreach ($line in $content) {
            $lines.Add($line)
        }
        $lines.Add("")

        Write-Host "  ✓ Merged: $($s.File) ($($content.Count) lines)" -ForegroundColor Green
    }
}

# -- 5. Write final file -----------------------------------------------------------
$lines | Set-Content $outPath -Encoding UTF8
Write-Host ""
Write-Host "✓ Merge complete: $outPath" -ForegroundColor Cyan

# -- 6. Clean up temp files --------------------------------------------------------
if (-not $KeepTmp) {
    $sections | ForEach-Object {
        $p = Join-Path $dir $_.File
        if (Test-Path $p) {
            Remove-Item $p -Force
            Write-Host "  ✓ Deleted: $($_.File)" -ForegroundColor DarkGray
        }
    }
    Write-Host "✓ Temporary files cleaned up" -ForegroundColor Cyan
} else {
    Write-Host "(-KeepTmp mode: temporary files retained)" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "Final blueprint file: $outPath" -ForegroundColor White
